apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.gateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image }}:{{ .Values.gateway.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.gateway.port }}
          env:
            - name: KSERVE_URL
              value: "http://{{ .Values.model.serviceName }}.default.svc.cluster.local:{{ .Values.model.port }}/v2/models/{{ .Values.model.name }}/infer"
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}