apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.gateway.name }}
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
      nodePort: {{ .Values.gateway.nodePort }}