apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-config
data:
  # Links the gateway to the model using internal Kubernetes DNS
  KSERVE_URL: "http://{{ .Values.model.serviceName }}:{{ .Values.model.port }}/v2/models/ocr-model/infer"