apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.model.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.model.name }}
    spec:
      containers:
        - name: model
          image: "{{ .Values.model.image }}:{{ .Values.model.tag }}"
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.model.resources | nindent 12 }}