# Global configuration
replicaCount: 1
imagePullSecretName: regcred

# API Gateway Settings
gateway:
  name: api-gateway
  serviceName: api-gateway-service
  image: "suranpickme/ocr-inference-platform" # Same repo
  tag: "api-gateway-v3"                           # Unique tag
  port: 8001
  nodePort: 30001
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"

# OCR Model Settings
model:
  name: ocr-model
  serviceName: ocr-model-service
  image: "suranpickme/ocr-inference-platform" # Same repo
  tag: "ocr-model-v3"                             # Unique tag
  port: 8080
  metricsPort: 8000
  resources:
    limits:
      memory: "1024Mi"
      cpu: "500m"