# Global configuration
replicaCount: 1
imagePullSecretName: regcred

# API Gateway Settings
gateway:
  name: api-gateway
  image: "suranpickme/ocr-inference-platform"
  tag: "api-gateway-v1"
  port: 8001
  nodePort: 30001
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"

# OCR Model Settings
model:
  name: ocr-model
  image: "suranpickme/ocr-inference-platform"
  tag: "ocr-model-v1"
  port: 8080
  resources:
    limits:
      memory: "1024Mi"
      cpu: "500m"